### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by MrSkwiggs** [goergisn/CodeInputField#2]
## There is no documentation for the following classes;
https://github.com/goergisn/CodeInputField/blob/b35d37f6bc298097db5de0b98fe52727f47c0640/Sources/CodeInputField/CodeInputField.swift#L4
https://github.com/goergisn/CodeInputField/blob/b35d37f6bc298097db5de0b98fe52727f47c0640/Sources/CodeInputField/CodeInputField%2BDefaultSegment.swift#L5
https://github.com/goergisn/CodeInputField/blob/b35d37f6bc298097db5de0b98fe52727f47c0640/Sources/CodeInputField/Digit.swift#L2

## Protocol requirements are not documented
https://github.com/goergisn/CodeInputField/blob/b35d37f6bc298097db5de0b98fe52727f47c0640/Sources/CodeInputField/CodeInputFieldSegment.swift#L6
https://github.com/goergisn/CodeInputField/blob/b35d37f6bc298097db5de0b98fe52727f47c0640/Sources/CodeInputField/CodeInputFieldSegment.swift#L7

**Comment by goergisn** [comment]
Should be resolved, thanks for mentioning 👍
